language: ruby

services:
  - redis-server

cache: bundler

addons:
  snaps:
  - name: docker
    channel: latest/beta

env:
  global:
    - PATH=/snap/bin:$PATH

jobs:
  include:
    - stage: "testing time"
      script: bundle exec rspec -f documentation --color --order rand spec
    - stage: ":ship: it to quay.io"
      ruby:
      services:
      script: make ship
      if: commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true

deploy:
  - provider: script
    script: make ship
    on:
      branch: master
