language: ruby

rvm: 2.3.1

sudo: false

cache: bundler

script: bundle exec rspec -fs --color --order rand spec

notifications:
  webhooks: http://requestb.in/14h19sy1

jobs:
  include:
    - stage: "testing time"
    - stage: ":ship: it to Quay.io"
      sudo: required
      dist: trusty
      install: skip
      script: ./script/docker-build-and-push
