language: ruby

services:
  - redis-server

cache: bundler

script: bundle exec rspec -f documentation --color --order rand spec


jobs:
  include:
    - stage: "testing time"
    - stage: ":ship: it to Quay.io"
      sudo: required
      dist: trusty
      ruby:
      services:
      addons:
      before_install: echo "skipping"
      install: echo "skipping"
      script: ./script/docker-build-and-push