language: ruby

rvm:
  - jruby-1.7.22
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk8

sudo: false

cache: bundler

script: bundle exec rspec -fs --color --order rand spec

notifications:
  webhooks: http://requestb.in/14h19sy1

matrix:
  include:
    - rvm: 2.2.2
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.2.2
      jdk: oraclejdk8
